services:
  back:
    develop:
      watch:
        - path: ./back/
          target: /app/
          action: sync
        - path: ./back/package.json
          action: rebuild

  front:
    develop:
      watch:
        - path: ./front/
          target: /app/
          action: sync
        - path: ./front/package.json
          action: rebuild