services:
  mysql-express:
    image: mysql:latest
    container_name: mysql-express
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_express
    ports:
      - 3306:3306
    volumes:
      - db_datas:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-express
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_host=mysql-express
      - DB_username=root
      - DB_password=123456
      - DB_database=db_express
      - DB_dialect=mysql
      - DB_port=3306
    develop:
      watch:
        - path: ./back/
          target: /app/
          action: sync
        - path: ./back/package.json
          action: rebuild
    depends_on:
      mysql-express:
        condition: service_healthy
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front-react
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./front/
          target: /app/
          action: sync
        - path: ./front/package.json
          action: rebuild
    depends_on:
      - back

volumes:
  db_datas: