services:
  mysql-express:
    image: mysql:latest
    container_name: mysql-express
    env_file:
      - ./mysql.env
    ports:
      - 3306:3306
    volumes:
      - db_datas:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-express
    ports:
      - 3000:3000
    env_file:
      - ./back/.env
    depends_on:
      mysql-express:
        condition: service_healthy
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front-react
    ports:
      - 8080:8080
    env_file:
      - ./front/.env
    depends_on:
      - back

volumes:
  db_datas: